[BPS]
bps_system =
bpsuser =
bpspass =

[SEARCH]
search_strikes =
number_of_filter =

[TP]
regular_package = DigitalVaccine
malware_package = ThreatDV
regular_package_cves = CVE-2023-27350
                       CVE-2023-28771
                       CVE-2023-3519
                       CVE-2023-46604
                       CVE-2023-22518

[DEP]
path = dep
tool = pkt2flow
pcap_name = consolidated.pcap

[AWS]
access_key_id =
secret_key =
bucket_name =
;prefix = new_pcaps
prefix = pcaps
tracker_file_url = https://dvlabs-breakingpoint-pcaps-test.s3.ap-south-1.amazonaws.com/artefacts/tracker_pcap.json
no_filter_cve_url = https://dvlabs-breakingpoint-pcaps-test.s3.ap-south-1.amazonaws.com/artefacts/no_filter_found_cve.json
pcaps_folder_url = https://dvlabs-breakingpoint-pcaps-test.s3.ap-south-1.amazonaws.com/pcaps/


[VAR]
test = automation-test
import_test_file = bp_night_run.bpt
new_strike_list_name = automation-strike-list
pcaps_folder = pcaps
new_cve_list_file = new_cve_list.json
dv_filters_list_file = dv_filters_list_file.json
;tracker_file = new_tracker_pcap.json
tracker_file = tracker_pcap.json
no_filter_found_file = no_filter_found_cve.json
artefacts_folder = artefacts

